// Auto-generated by scripts/build-thumb-manifest.mjs (prebuild step).
// Don't edit by hand.
export const thumbManifest = {
  "articleThumbs": [
    "barucker-video.jpg",
    "berliner-zeitung-becchi-interview.jpg",
    "freie-medienakademie-buttkereit-rezension.jpg",
    "multipolar-schreyer-rezension.jpg",
    "nachdenkseiten-gosch-rezension.jpg",
    "overton-delapuente-interview.jpg",
    "skambraks-berliner-rezension.jpg",
    "tichys-leyhausen-rezension.jpg",
    "weltwoche-zeller-video.jpg"
  ],
  "faktencheckThumbs": [
    "afp-faktencheck.jpg",
    "ard-faktenfinder-merz.jpg",
    "ard-siggelkow-ueber-sanktionen.jpg",
    "correctiv-anti-journalisten.jpg",
    "correctiv-nanolipide.jpg",
    "dw-ndr-rostock.jpg",
    "faktenfinder-watzl.jpg",
    "ganser-guerot-krone.jpg",
    "pflanzensprengstoff.jpg",
    "pistorius-faktenfuchs.jpg",
    "siggelkow-rechtsextremismus.jpg",
    "siggelkow-uebersterblichkeit.jpg",
    "spahn-wieler-faktenchecker.jpg",
    "spannungsfall-dpa.jpg",
    "tagesschau-vitamin-d.jpg",
    "transgender-gesetz-tagesschau.jpg",
    "zdf-nordstream-sabotage.jpg",
    "zdf-nordstream.jpg"
  ],
  "ytThumbs": [
    "VqPFYDL9s3s.jpg",
    "jmKAuP1E2jA.jpg"
  ],
  "chronikThumbs": [
    "who-climate-health.jpg"
  ]
} as const;
